package:
  name: bird
  version: 2.0.12
  epoch: 0
  description: BIRD Internet Routing Daemon
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-or-later
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - libssh-dev
      - linux-headers
      - ncurses-dev
      - readline-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 3ec462a237d06d1f4455d6ec00a42f0b1686061fc988e5c89a841d01dd753b53
      uri: https://bird.network.cz/download/bird-${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: bird-make-test-bsprintf.patch
  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --runstatedir=/run \
        --enable-libssh
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip