package:
  name: conntrack-tools
  version: 1.4.7
  epoch: 0
  description: Connection tracking userspace tools
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-or-later
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - libmnl-dev
      # - libnetfilter_conntrack-dev
      # - libnetfilter_cthelper-dev
      # - libnetfilter_cttimeout-dev
      # - libnetfilter_queue-dev
      - libnfnetlink-dev@local
      # - libtirpc-dev
      - linux-headers

pipeline:
  - uses: fetch
    with:
      expected-sha256: 099debcf57e81690ced57f516b493588a73518f48c14d656f823b29b4fc24b5d
      uri: https://www.netfilter.org/projects/conntrack-tools/files/conntrack-tools-${{package.version}}.tar.bz2
  - uses: autoconf/configure
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip