package:
  name: ctop
  version: 0.7.7
  epoch: 0
  description: Top-like interface for container metrics
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - go
pipeline:
  - uses: fetch
    with:
      expected-sha512: 9924c4dc5da489f90b029bc8060e759edf02a170e17bbc9f9c29b6536e5bc3e5eec69af829c7662a1f69cd331fc24022cae8b30e865a07742fd7e3623bc7f33f
      uri: https://github.com/bcicen/ctop/archive/refs/tags/v${{package.version}}.tar.gz
  - runs: |
      make build
      install -Dm755 ctop "${{targets.destdir}}"/usr/bin/ctop