package:
  name: dhcping
  version: 1.2
  epoch: 0
  description: dhcp daemon ping program
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-2-Clause
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
pipeline:
  - uses: fetch
    with:
      expected-sha256: 32ef86959b0bdce4b33d4b2b216eee7148f7de7037ced81b2116210bc7d3646a
      uri: http://www.mavetju.org/download/dhcping-${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: fix-endless-getopt-loop.patch
  - uses: autoconf/configure
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip