package:
  name: ethtool
  version: 6.2
  epoch: 0
  description: Utility for controlling network drivers and hardware
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-only
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - linux-headers
      - libmnl-dev@local

pipeline:
  - uses: fetch
    with:
      expected-sha256: 86df0114064d4d73f6bf72bf03e85c33964a519ee0c1d1ba65005ad2d0e570e1
      uri: https://www.kernel.org/pub/software/network/ethtool/ethtool-${{package.version}}.tar.xz
  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --mandir=/usr/share/man
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip