package:
  name: fping
  version: 5.1
  epoch: 0
  description: A utility to ping multiple hosts at once
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-only
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - linux-headers
      - libmnl-dev@local

pipeline:
  - uses: fetch
    with:
      expected-sha256: 1ee5268c063d76646af2b4426052e7d81a42b657e6a77d8e7d3d2e60fd7409fe
      uri: https://fping.org/dist/fping-${{package.version}}.tar.gz
  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --mandir=/usr/share/man \
        --enable-ipv6
  - uses: autoconf/make
  - uses: autoconf/make-install
  - runs: |
      setcap cap_net_raw=+ep "${{targets.destdir}}"/usr/sbin/fping
  - uses: strip