package:
  name: grpcurl
  version: 1.8.7
  epoch: 0
  description: CLI tool to interact with gRPC servers
  target-architecture:
    - all
  copyright:
    - license: MIT
      paths:
        - "*"
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - build-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: 7f7a59f8a5ef8833d30a94e1c36ddb0d76bab1ae64cd5c8bcb87d42e877c3bca
      uri: https://github.com/fullstorydev/grpcurl/archive/refs/tags/v${{package.version}}.tar.gz
  - runs: |
      go build -v -ldflags "-X main.version=v${{package.version}}" ./cmd/grpcurl/
      install -Dm755 grpcurl "${{targets.destdir}}"/usr/bin/grpcurl
  - uses: strip