package:
  name: iftop
  version: 0.17
  epoch: 0
  description: A tool to display bandwidth usage on an interface
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-or-later
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libpcap-dev@local
      - ncurses-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: d032547c708307159ff5fd0df23ebd3cfa7799c31536fa0aea1820318a8e0eac
      uri: https://www.ex-parrot.com/~pdw/iftop/download/iftop-${{package.version}}.tar.gz
  - uses: autoconf/configure
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip