package:
  name: iperf3
  version: 3.13
  epoch: 0
  description: A tool to measure IP bandwidth using UDP or TCP
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-3-Clause-LBNL
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - openssl-dev
pipeline:
  - uses: fetch
    with:
      expected-sha256: a49d23fe0d3b1482047ad7f3b9e384c69657a63b486c4e3f0ce512a077d94434
      uri: https://github.com/esnet/iperf/archive/${{package.version}}.tar.gz
  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --disable-static
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: "iperf3-dev"
    description: "headers for iperf3"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - iperf3