package:
  name: iperf
  version: 2.1.8
  epoch: 0
  description: A tool to measure IP bandwidth using UDP or TCP
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: NCSA
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - linux-headers
pipeline:
  - uses: fetch
    with:
      expected-sha256: 8e2cf2fbc9d0d4d1cf9d109b1e328459f9622993dc9a4c5a7dc8a2088fb7beaf
      uri: https://sourceforge.net/projects/iperf2/files/iperf-${{package.version}}.tar.gz
  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
