package:
  name: ipvsadm
  version: 1.31
  epoch: 0
  description: The IP Virtual Server administration utility
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-or-later
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - linux-headers
      - libnl3-dev
      - popt-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 1a0a5e25b5a1226435d2fb76341656f83a710183aebb0d204db39c0ec3bedfdb
      uri: https://kernel.org/pub/linux/utils/kernel/ipvsadm/ipvsadm-${{package.version}}.tar.xz
  - runs: |
      make libs && make BUILD_ROOT="${{targets.destdir}}" \
        MANDIR=usr/share/man \
        SBIN="${{targets.destdir}}/usr/sbin" \
        INIT="${{targets.destdir}}/etc/init.d"

      make -j1 BUILD_ROOT="${{targets.destdir}}" \
        MANDIR=usr/share/man \
        SBIN="${{targets.destdir}}/usr/sbin" \
        INIT="${{targets.destdir}}/etc/init.d" \
        install
  - uses: strip