package:
  name: libcap
  version: 2.6.7
  epoch: 0
  description: POSIX 1003.1e capabilities
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-3-Clause OR GPL-2.0-only
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - linux-headers
      - perl
      - bash

pipeline:
  - uses: fetch
    with:
      expected-sha256: 1ee5268c063d76646af2b4426052e7d81a42b657e6a77d8e7d3d2e60fd7409fe
      uri: https://fping.org/dist/fping-${{package.version}}.tar.gz
  - runs: |
      make BUILD_CC=gcc CC="${CC:-gcc}" lib=lib prefix=/usr GOLANG=no DESTDIR="$pkgdir"
  - uses: strip
subpackages:
  - name: "libcap-utils"
    description: "libcap (utils)"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr