package:
  name: libmnl
  version: 1.0.5
  epoch: 0
  description: Library for minimalistic netlink
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: LGPL-2.1-or-later
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - linux-headers
      # - bsd-compat-headers

pipeline:
  - uses: fetch
    with:
      expected-sha256: 274b9b919ef3152bfb3da3a13c950dd60d6e2bcd54230ffeca298d03b40d0525
      uri: https://www.netfilter.org/projects/libmnl/files/libmnl-${{package.version}}.tar.bz2
  - uses: patch
    with:
      patches: fix-musl-headers.patch
  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --enable-static
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: "libmnl-dev"
    description: "headers for libmnl"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libmnl