package:
  name: libnet
  version: 1.2
  epoch: 0
  description: A generic networking API that provides access to several protocols
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-2-Clause
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
pipeline:
  - uses: fetch
    with:
      expected-sha256: caa4868157d9e5f32e9c7eac9461efeff30cb28357f7f6bf07e73933fb4edaa7
      uri: https://github.com/libnet/libnet/releases/download/v${{package.version}}/libnet-${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: fix-types.patch
  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --with-link-layer=linux
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
  - runs: tree
subpackages:
  - name: "libnet-dev"
    description: "headers for libnet"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libnet
  # - name: libnet-static
  #   description: libnet static
  #   pipeline:
  #     - uses: split/static
  # - name: libnet-doc
  #   description: libnet manpages
  #   pipeline:
  #     - uses: split/manpages