package:
  name: libnl3
  version: 3.7.0
  epoch: 0
  description: Library for applications dealing with netlink sockets
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: LGPL-2.1-or-later
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - linux-headers
      - flex
      - bison
      - libtool

pipeline:
  - uses: fetch
    with:
      expected-sha256: 9fe43ccbeeea72c653bdcf8c93332583135cda46a79507bfd0a483bb57f65939
      uri: https://github.com/thom311/libnl/releases/download/libnl3_7_0/libnl-${{targets.destdir}}.tar.gz
  - uses: patch
    with:
      patches: libnl-musl.patch
  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --disable-static \
        --enable-unit-tests
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: "libnl3-dev"
    description: "headers for libnl3"
    pipeline:
      - uses: split/dev
  - name: "libnl3-cli"
    description: "Command line interface utils for libnl3"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/lib/libnl-cli*.so.* \
            "${{targets.destdir}}"/usr/lib/libnl \
            "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/bin "${{targets.subpkgdir}}"/usr/