package:
  name: libpcap
  version: 1.10.3
  epoch: 0
  description: A system-independent interface for user-level packet capture
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-3-Clause
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - bison
      - flex
      - linux-headers
pipeline:
  - uses: fetch
    with:
      expected-sha256: 2a8885c403516cf7b0933ed4b14d6caa30e02052489ebd414dc75ac52e7559e6
      uri: https://www.tcpdump.org/release/libpcap-${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: fix-headers.patch
  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --enable-ipv6
  - runs: |
      ./config.status
      make all shared
      make -j1 DESTDIR="${{targets.destdir}}" install install-shared
  - uses: strip
subpackages:
  - name: "libpcap-dev"
    description: "headers for libpcap"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libpcap