package:
  name: libssh
  version: 0.10.4
  epoch: 0
  description: Library for accessing ssh client services through C libraries
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: LGPL-2.1-or-later BSD-2-Clause
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - samurai
      - openssl-dev
      - zlib-dev
      - xz

pipeline:
  - uses: fetch
    with:
      expected-sha512: 01ee52d480201d9886c15e81137c185334b404d1c8e8b743ddf58e95fe8619c8c013616a49807bd1111fde72fa177cd35f3c22b66cbf5d720b5abfacdf7601ed
      uri: https://www.libssh.org/files/0.10/libssh-${{package.version}}.tar.xz
  - runs: |
      cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DWITH_GSSAPI=OFF \
        -DUNIT_TESTING=OFF
      cmake --build build
      DESTDIR="${{targets.destdir}}" cmake --install build
  - uses: strip
subpackages:
  - name: "libssh-dev"
    description: "headers for libssh"
    pipeline:
      - uses: split/dev