package:
  name: nmap
  version: 7.93
  epoch: 0
  description: network exploration tool and security/port scanner
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: custom
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libpcap-dev@local
      - libssh2-dev
      - linux-headers
      - lua5.3-dev
      - openssl-dev
      - pcre-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha512: 4ec9295e25bd7a215e718c3dbbf09bfe6339b60850f4a8d09b5ad0cbf41a0da8ece0168efc5ca91ba1ecbd83b1d31735d77dacd5f1ec1a9fd212454dd1f0f0fd
      uri: https://nmap.org/dist/nmap-${{package.version}}.tar.bz2
  - uses: patch
    with:
      patches: fortify-source.patch
  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --without-zenmap \
        --with-openssl=yes \
        --with-libpcap=yes \
        --with-libpcre=yes \
        --with-libz=yes \
        --with-libssh2=yes \
        --with-liblua=/usr/lib/lua5.3
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: "nmap-scripts"
    description: "nmap (scripts)"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/nmap/
          mv ${{targets.destdir}}/usr/share/nmap/scripts ${{targets.subpkgdir}}/usr/share/nmap/
  - name: "nmap-nselibs"
    description: "nmap (nselibs)"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/nmap/nselib
          mv ${{targets.destdir}}/usr/share/nmap/nse_main.lua ${{targets.subpkgdir}}/usr/share/nmap/
          mv ${{targets.destdir}}/usr/share/nmap/nselib ${{targets.subpkgdir}}/usr/share/nmap/
  - name: "nmap-ncat"
    description: "nmap (ncat tool)"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/ncat ${{targets.subpkgdir}}/usr/bin/
  - name: "nmap-nping"
    description: "nmap (nping tool)"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/nping ${{targets.subpkgdir}}/usr/bin/