package:
  name: socat
  version: 1.7.4.4
  epoch: 0
  description: Multipurpose relay for binary protocols
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-only WITH OpenSSL-Exception
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - openssl-dev
      - readline-dev
      - linux-headers
pipeline:
  - uses: fetch
    with:
      expected-sha256: 0f8f4b9d5c60b8c53d17b60d79ababc4a0f51b3bb6d2bd3ae8a6a4b9d68f195e
      uri: http://www.dest-unreach.org/socat/download/socat-${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: netdb-internal.patch use-linux-headers.patch
  - uses: autoconf/configure
  - runs: |
      make
      make DESTDIR="${{targets.destdir}}" install
  - uses: strip

subpackages:
  - name: socat-doc
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/socat
          install -m644 EXAMPLES doc/*.html doc/*.css "${{targets.subpkgdir}}"/usr/share/socat