package:
  name: tcpdump
  version: 4.99.3
  epoch: 0
  description: A tool for network monitoring and data acquisition
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-3-Clause
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - samurai
      - openssl-dev
      - libpcap-dev@local

pipeline:
  - uses: fetch
    with:
      expected-sha256: ad75a6ed3dc0d9732945b2e5483cb41dc8b4b528a169315e499c6861952e73b3
      uri: https://www.tcpdump.org/release/tcpdump-${{package.version}}.tar.gz
  # - uses: cmake/build
  # - uses: cmake/install
  - runs: |
      cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr
      cmake --build build
      DESTDIR="${{targets.destdir}}" cmake --install build
  - uses: strip
