package:
  name: tcptraceroute
  version: 1.5b7
  epoch: 0
  description: Display route path using TCP probes
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-only
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - libpcap-dev@local
      - libnet-dev@local
pipeline:
  - uses: fetch
    with:
      expected-sha256: 57fd2e444935bc5be8682c302994ba218a7c738c3a6cae00593a866cd85be8e7
      uri: https://github.com/mct/tcptraceroute/archive/tcptraceroute-1.5beta7.tar.gz
  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip