package:
  name: websocat
  version: 1.11.0
  epoch: 0
  description: Netcat, curl and socat for WebSockets
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - ca-certificates-bundle
      - build-base
      - bash
      - rust
      - openssl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/vi/websocat/archive/v${{package.version}}/websocat-${{package.version}}.tar.gz
      expected-sha256: 943d6f66045658cca7341dd89fe1c2f5bdac62f4a3c7be40251b810bc811794f
  - name: Configure and build
    runs: |
      cargo build --release --locked
      mkdir -p ${{targets.destdir}}/usr
      install -D -m 0755 "target/release/websocat" -t "${{targets.destdir}}/usr/bin"
